"""Render a static exec dashboard (dashboard/index.html) from the marts.

Zero-server demo artifact: queries DuckDB, embeds the numbers as JSON,
draws with Chart.js (CDN). For interactive BI, point Metabase at the same
DuckDB file (see README).
"""

from __future__ import annotations

import json
from pathlib import Path

import duckdb

ROOT = Path(__file__).resolve().parents[1]
DB = ROOT / "warehouse" / "funnel.duckdb"
OUT = ROOT / "dashboard" / "index.html"


def rows(con, sql: str) -> list[dict]:
    cur = con.execute(sql)
    cols = [d[0] for d in cur.description]
    return [dict(zip(cols, r)) for r in cur.fetchall()]


def main() -> None:
    con = duckdb.connect(str(DB), read_only=True)
    sc = "main_marts.mart_executive_scorecard"

    kpi = rows(con, f"""
        select sum(leads) leads, sum(visited) visited, sum(purchased) purchased,
               sum(revenue) revenue, round(sum(paid_spend)) spend,
               round(sum(paid_spend)/nullif(sum(purchased),0)) cac
        from {sc}""")[0]
    funnel = rows(con, f"""
        select sum(leads) a, sum(qualified) b, sum(booked) c,
               sum(visited) d, sum(purchased) e from {sc}""")[0]
    monthly = rows(con, f"""
        select year_month, sum(revenue) revenue, round(sum(paid_spend)) spend,
               sum(purchased) purchased
        from {sc} group by 1 order by 1""")
    cr_city = rows(con, f"""
        select year_month, city, cr_lead_qualified_pct
        from {sc} order by 1, 2""")
    scorecard = rows(con, f"select * from {sc} order by year_month desc, city limit 18")

    payload = {
        "kpi": kpi,
        "funnel": [funnel["a"], funnel["b"], funnel["c"], funnel["d"], funnel["e"]],
        "monthly": monthly,
        "cr_city": cr_city,
        "scorecard": scorecard,
    }

    html = TEMPLATE.replace("__DATA__", json.dumps(payload, default=str))
    OUT.write_text(html, encoding="utf-8")
    print(f"wrote {OUT}")


TEMPLATE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>FitFlow Growth Scorecard (synthetic demo)</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4"></script>
<style>
 body{font-family:system-ui,sans-serif;margin:24px;background:#0f172a;color:#e2e8f0}
 h1{font-size:20px} .muted{color:#94a3b8;font-size:12px}
 .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px;margin:16px 0}
 .card{background:#1e293b;border-radius:10px;padding:14px}
 .card .v{font-size:22px;font-weight:700} .card .l{font-size:12px;color:#94a3b8}
 .charts{display:grid;grid-template-columns:1fr 1fr;gap:16px}
 .panel{background:#1e293b;border-radius:10px;padding:14px}
 table{width:100%;border-collapse:collapse;font-size:12px;margin-top:8px}
 th,td{padding:6px 8px;text-align:right;border-bottom:1px solid #334155}
 th:first-child,td:first-child,th:nth-child(2),td:nth-child(2){text-align:left}
 @media(max-width:900px){.charts{grid-template-columns:1fr}}
</style></head><body>
<h1>FitFlow Studios: Growth Scorecard</h1>
<div class="muted">100% synthetic data · generated by this repo · fictional company</div>
<div class="grid" id="kpis"></div>
<div class="charts">
 <div class="panel"><canvas id="funnel"></canvas></div>
 <div class="panel"><canvas id="trend"></canvas></div>
 <div class="panel" style="grid-column:1/-1"><canvas id="crcity"></canvas>
  <div class="muted">Lead→qualified % by city, watch Crestline from Sep 2025 (scripted anomaly the blended average hides)</div>
 </div>
</div>
<div class="panel" style="margin-top:16px"><b>Latest months × city</b><div id="tbl"></div></div>
<script>
const D=__DATA__;
const fmt=n=>n==null?'–':Number(n).toLocaleString();
const rp=n=>n==null?'–':'Rp '+(n/1e6).toFixed(1)+' jt';
const K=[['Leads',fmt(D.kpi.leads)],['Trial visits',fmt(D.kpi.visited)],
 ['New members',fmt(D.kpi.purchased)],['Revenue',rp(D.kpi.revenue)],
 ['Paid spend',rp(D.kpi.spend)],['Blended CAC',rp(D.kpi.cac)]];
document.getElementById('kpis').innerHTML=K.map(([l,v])=>
 `<div class="card"><div class="v">${v}</div><div class="l">${l}</div></div>`).join('');
Chart.defaults.color='#94a3b8';
new Chart(funnel,{type:'bar',data:{labels:['Leads','Qualified','Booked','Visited','Purchased'],
 datasets:[{data:D.funnel,backgroundColor:['#334155','#475569','#64748b','#22c55e','#16a34a']}]},
 options:{plugins:{legend:{display:false},title:{display:true,text:'Funnel (12 months)'}}}});
new Chart(trend,{type:'line',data:{labels:D.monthly.map(m=>m.year_month),
 datasets:[{label:'Revenue',data:D.monthly.map(m=>m.revenue),borderColor:'#22c55e',yAxisID:'y'},
  {label:'Paid spend',data:D.monthly.map(m=>m.spend),borderColor:'#f59e0b',yAxisID:'y'}]},
 options:{plugins:{title:{display:true,text:'Revenue vs spend by month'}}}});
const cities=[...new Set(D.cr_city.map(r=>r.city))];
const months=[...new Set(D.cr_city.map(r=>r.year_month))];
const colors={Arden:'#38bdf8',Brightwater:'#a78bfa',Crestline:'#f87171'};
new Chart(crcity,{type:'line',data:{labels:months,datasets:cities.map(c=>({label:c,
 data:months.map(m=>{const r=D.cr_city.find(x=>x.city===c&&x.year_month===m);return r?r.cr_lead_qualified_pct:null}),
 borderColor:colors[c]||'#ccc'}))},
 options:{plugins:{title:{display:true,text:'Lead → Qualified % by city'}}}});
const cols=['year_month','city','leads','visited','purchased','revenue','paid_spend','cac','roas','revenue_attainment_pct'];
document.getElementById('tbl').innerHTML='<table><tr>'+cols.map(c=>`<th>${c}</th>`).join('')+'</tr>'+
 D.scorecard.map(r=>'<tr>'+cols.map(c=>`<td>${typeof r[c]==='number'?fmt(r[c]):(r[c]??'–')}</td>`).join('')+'</tr>').join('')+'</table>';
</script></body></html>
"""

if __name__ == "__main__":
    main()
